### ISSUE TITLE
Windows test failures

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/module-ballerina-http#62]
```
	[fail] test408Response:
	    Assertion Failed!
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertTrue(assert.bal:52)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.http.16-idle-timeout-response-test:test408Response(tests/integration-tests/service/http/16-idle-timeout-response-test.bal:77)

	[fail] testXmlPayloadWithDefaultCharset:
	    Assertion Failed!
	    	expected: '<????><name>????</name></????>'
	    	actual	: '<????><name>�?�鸟驿站</name></????>'
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.unit-tests.entity.entity-body-with-charset-test:testXmlPayloadWithDefaultCharset(tests/unit-tests/entity/entity-body-with-charset-test.bal:117)

	[fail] testXmlPayloadWithCharset:
	    Assertion Failed!
	    	expected: '<????><name>????</name></????>'
	    	actual	: '<????><name>�?�鸟驿站</name></????>'
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.unit-tests.entity.entity-body-with-charset-test:testXmlPayloadWithCharset(tests/unit-tests/entity/entity-body-with-charset-test.bal:129)

	[fail] jsonTest:
	    Found unexpected output
	    	expected: '{"test":"????"}'
	    	actual	: '{"test":"????"}'
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.test-commons:assertJsonPayload(tests/test-commons.bal:76)
	    	ballerina.http-tests.1_0_0.tests.unit-tests.entity.entity-body-with-charset-test:jsonTest(tests/unit-tests/entity/entity-body-with-charset-test.bal:314)
```

**Comment by niveathika** [comment]
Observed following intermittent test failures
```
[fail] testCookieSupport:
	    Assertion Failed!
	    	expected: 'Hello World!'
	    	actual	: ''
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.37_cookie_client:testCookieSupport(tests/integration-tests/service/websocket/37_cookie_client.bal:81)

	[fail] IncorrectCookieTestCase:
	    Assertion Failed!
	    	expected: 'InvalidHandshakeError: Invalid handshake response getStatus: 401 Unauthorized'
	    	actual	: ''
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.38_incorrect_cookie:IncorrectCookieTestCase(tests/integration-tests/service/websocket/38_incorrect_cookie.bal:78)

	[fail] testBasicAuthenticationSuccess:
	    Assertion Failed!
	    	expected: 'Hello World!'
	    	actual	: ''
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.39_authentication_success_client:testBasicAuthenticationSuccess(tests/integration-tests/service/websocket/39_authentication_success_client.bal:65)

	[fail] testBasicAuthenticationFailure:
	    Assertion Failed!
	    	expected: 'InvalidHandshakeError: Invalid handshake response getStatus: 401 Unauthorized'
	    	actual	: ''
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.41_authentication_failure_client:testBasicAuthenticationFailure(tests/integration-tests/service/websocket/41_authentication_failure_client.bal:60)

	[fail] testBinaryFrameWithThirdServer:
	    Assertion Failed!
	    	expected: 'Hello'
	    	actual	: ''
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.43_failover_client:testBinaryFrameWithThirdServer(tests/integration-tests/service/websocket/43_failover_client.bal:81)

	[fail] testTextFrameWithSecondServer:
	    Assertion Failed!
	    	expected: 'Hello'
	    	actual	: ''
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.43_failover_client:testTextFrameWithSecondServer(tests/integration-tests/service/websocket/43_failover_client.bal:99)

	[fail] testBinaryFrameWithFirstServer:
	    {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'string'"}
	    	at ballerina.test.0_0_0:getBallerinaType(assert.bal:162)
	    	ballerina.test.0_0_0:getInequalityErrorMsg(assert.bal:138)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:74)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.43_failover_client:testBinaryFrameWithFirstServer(tests/integration-tests/service/websocket/43_failover_client.bal:118)

	[fail] testHandshakeTimeout:
	    Assertion Failed!
	    	expected: 'Hello everyone'
	    	actual	: ''
	    	at ballerina.test.0_0_0:createBallerinaError(assert.bal:42)
	    	ballerina.test.0_0_0:assertEquals(assert.bal:75)
	    	ballerina.http-tests.1_0_0.tests.integration-tests.service.websocket.43_failover_client:testHandshakeTimeout(tests/integration-tests/service/websocket/43_failover_client.bal:136)
```

**Comment by chamil321** [comment]
Observed another intermittent failure

```
Transport test suite > Transport HTTP test > org.ballerinalang.net.transport.http1point0test.ChunkAlwaysHttpOnePointZeroClientTestCase STANDARD_OUT
2020-10-12T04:18:46.2509485Z     Start Running Chunk Always Http One Point Zero Client Test Case ...
2020-10-12T04:18:46.2515779Z 
2020-10-12T04:18:46.2519553Z Transport test suite > Transport HTTP test > org.ballerinalang.net.transport.http1point0test.ChunkAlwaysHttpOnePointZeroClientTestCase STANDARD_ERROR
2020-10-12T04:18:46.2522965Z     Oct 12, 2020 4:18:46 AM org.ballerinalang.net.transport.util.server.HttpServer start
2020-10-12T04:18:46.2524951Z     INFO: HttpServer started on port 9000
2020-10-12T04:18:46.2526196Z     Oct 12, 2020 4:18:46 AM org.ballerinalang.net.transport.util.TestNGListener onTestStart
2020-10-12T04:18:46.2527336Z     INFO: Test running: postTest
2020-10-12T04:18:46.2527767Z 
2020-10-12T04:18:46.2557107Z Transport test suite > Transport HTTP test > org.ballerinalang.net.transport.http1point0test.ChunkAlwaysHttpOnePointZeroClientTestCase > postTest STANDARD_ERROR
2020-10-12T04:18:46.2561394Z     Oct 12, 2020 4:18:46 AM org.ballerinalang.net.transport.contractimpl.sender.states.ReceivingEntityBody writeOutboundRequestEntity
2020-10-12T04:18:46.3071793Z     WARNING: writeOutboundRequestEntity is not a valid action of this state
2020-10-12T04:18:46.3074088Z     Oct 12, 2020 4:18:46 AM org.ballerinalang.net.transport.util.TestUtil handleException
2020-10-12T04:18:46.3075814Z     SEVERE: Exception occurred while running postTest
2020-10-12T04:18:46.3077590Z     io.netty.handler.codec.EncoderException: java.io.IOException: Inbound response message already received
2020-10-12T04:18:46.3081706Z     	at org.ballerinalang.net.transport.message.HttpMessageDataStreamer$ByteBufferOutputStream.close(HttpMessageDataStreamer.java:170)
2020-10-12T04:18:46.3087273Z     	at org.ballerinalang.net.transport.chunkdisable.ChunkClientTemplate.sendRequest(ChunkClientTemplate.java:79)
2020-10-12T04:18:46.3095326Z     	at org.ballerinalang.net.transport.http1point0test.ChunkAlwaysHttpOnePointZeroClientTestCase.postTest(ChunkAlwaysHttpOnePointZeroClientTestCase.java:46)
2020-10-12T04:18:46.3101814Z     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-12T04:18:46.3105239Z     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-12T04:18:46.3109379Z     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-12T04:18:46.3112260Z     	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-12T04:18:46.3114935Z     	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
2020-10-12T04:18:46.3117781Z     	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
2020-10-12T04:18:46.3119964Z     	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
2020-10-12T04:18:46.3122278Z     	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
2020-10-12T04:18:46.3124510Z     	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
2020-10-12T04:18:46.3126283Z     	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
2020-10-12T04:18:46.3127382Z     	at org.testng.TestRunner.privateRun(TestRunner.java:648)
2020-10-12T04:18:46.3128204Z     	at org.testng.TestRunner.run(TestRunner.java:505)
2020-10-12T04:18:46.3129005Z     	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
2020-10-12T04:18:46.3130024Z     	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
2020-10-12T04:18:46.3131055Z     	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
2020-10-12T04:18:46.3132138Z     	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
2020-10-12T04:18:46.3133197Z     	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
2020-10-12T04:18:46.3134500Z     	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
2020-10-12T04:18:46.3135653Z     	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
2020-10-12T04:18:46.3136708Z     	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
2020-10-12T04:18:46.3137618Z     	at org.testng.TestNG.runSuites(TestNG.java:1049)
2020-10-12T04:18:46.3138300Z     	at org.testng.TestNG.run(TestNG.java:1017)
2020-10-12T04:18:46.3140491Z     	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
2020-10-12T04:18:46.3143714Z     	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
2020-10-12T04:18:46.3146809Z     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
2020-10-12T04:18:46.3149140Z     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-12T04:18:46.3151263Z     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-12T04:18:46.3153663Z     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-12T04:18:46.3155414Z     	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-12T04:18:46.3156969Z     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2020-10-12T04:18:46.3159095Z     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2020-10-12T04:18:46.3161630Z     	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2020-10-12T04:18:46.3164359Z     	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2020-10-12T04:18:46.3165927Z     	at com.sun.proxy.$Proxy5.stop(Unknown Source)
2020-10-12T04:18:46.3167284Z     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
2020-10-12T04:18:46.3169348Z     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-12T04:18:46.3171241Z     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-12T04:18:46.3173462Z     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-12T04:18:46.3175381Z     	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-12T04:18:46.3176942Z     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2020-10-12T04:18:46.3179057Z     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2020-10-12T04:18:46.3182118Z     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
2020-10-12T04:18:46.3186019Z     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
2020-10-12T04:18:46.3188818Z     	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
2020-10-12T04:18:46.3190857Z     	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2020-10-12T04:18:46.3192936Z     	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2020-10-12T04:18:46.3194844Z     	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-10-12T04:18:46.3196573Z     	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-10-12T04:18:46.3198432Z     	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2020-10-12T04:18:46.3199849Z     	at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-12T04:18:46.3200652Z     Caused by: java.io.IOException: Inbound response message already received
2020-10-12T04:18:46.3203844Z     	at org.ballerinalang.net.transport.contractimpl.sender.states.SendingEntityBody.readInboundResponseHeaders(SendingEntityBody.java:90)
2020-10-12T04:18:46.3209879Z     	at org.ballerinalang.net.transport.contractimpl.common.states.SenderReqRespStateManager.readInboundResponseHeaders(SenderReqRespStateManager.java:54)
2020-10-12T04:18:46.3215219Z     	at org.ballerinalang.net.transport.contractimpl.sender.TargetHandler.channelRead(TargetHandler.java:85)
2020-10-12T04:18:46.3218378Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
2020-10-12T04:18:46.3221371Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
2020-10-12T04:18:46.3224273Z     	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
2020-10-12T04:18:46.3226771Z     	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
2020-10-12T04:18:46.3229454Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
2020-10-12T04:18:46.3232431Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
2020-10-12T04:18:46.3235311Z     	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
2020-10-12T04:18:46.3237938Z     	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2020-10-12T04:18:46.3240605Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
2020-10-12T04:18:46.3243606Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
2020-10-12T04:18:46.3246486Z     	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
2020-10-12T04:18:46.3249528Z     	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2020-10-12T04:18:46.3252385Z     	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
2020-10-12T04:18:46.3254644Z     	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
2020-10-12T04:18:46.3256992Z     	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2020-10-12T04:18:46.3259752Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
2020-10-12T04:18:46.3262688Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
2020-10-12T04:18:46.3265589Z     	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
2020-10-12T04:18:46.3267912Z     	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2020-10-12T04:18:46.3270373Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
2020-10-12T04:18:46.3273365Z     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
2020-10-12T04:18:46.3275935Z     	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2020-10-12T04:18:46.3277980Z     	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2020-10-12T04:18:46.3279917Z     	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
2020-10-12T04:18:46.3282067Z     	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2020-10-12T04:18:46.3284126Z     	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2020-10-12T04:18:46.3285670Z     	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2020-10-12T04:18:46.3287299Z     	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2020-10-12T04:18:46.3289054Z     	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2020-10-12T04:18:46.3290842Z     	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-10-12T04:18:46.3292025Z     	... 1 more
2020-10-12T04:18:46.3292239Z 
2020-10-12T04:18:46.3293229Z     Oct 12, 2020 4:18:46 AM org.ballerinalang.net.transport.util.TestNGListener onTestFailure
2020-10-12T04:18:46.3294448Z     SEVERE: Test failed: postTest-> Exception occurred while running postTest
2020-10-12T04:18:46.3294831Z 
2020-10-12T04:18:46.3297183Z Transport test suite > Transport HTTP test > org.ballerinalang.net.transport.http1point0test.ChunkAlwaysHttpOnePointZeroClientTestCase > postTest FAILED
2020-10-12T04:18:46.3300246Z     java.lang.AssertionError at ChunkAlwaysHttpOnePointZeroClientTestCase.java:59
2020-10-12T04:18:48.3077432Z 
2020-10-12T04:18:48.3078756Z Transport test suite > Transport HTTP test STANDARD_ERROR
2020-10-12T04:18:48.3082131Z     Oct 12, 2020 4:18:48 AM org.ballerinalang.net.transport.contractimpl.common.states.StateUtil handleIncompleteInboundMessage
2020-10-12T04:18:48.3085649Z     WARNING: Remote host closed the connection while reading inbound response body
2020-10-12T04:18:50.3146035Z     Oct 12, 2020 4:18:50 AM org.ballerinalang.net.transport.util.server.HttpServer shutdown
2020-10-12T04:18:50.3147187Z     INFO: HttpServer shutdown
2020-10-12T04:18:50.3147458Z 

```
